version: 1.0.{build}
image: Visual Studio 2019
clone_folder: c:\anson\bcvp
install:
- ps: ''
before_build:
- cmd: dotnet restore
- choco install opencover.portable
- choco install codecov
build:
  verbosity: minimal
test_script:
- OpenCover.Console.exe -target:"dotnet.exe" -targetargs:"test" -output:coverage.xml -register:user -filter:"+[*]* -[*Moq]* -[xunit*]*" -oldstyle
- codecov -f "coverage.xml"
